name: ci-dev.yml

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  unit-test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.8'
          distribution: 'temurin'
          cache: gradle
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  integration-test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.8'
          distribution: 'temurin'
          cache: gradle
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  apk:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Generate APK
    runs-on: ubuntu-latest
    needs: [ unit-test, integration-test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.8'
          distribution: 'temurin'
          cache: gradle
      - name: Build debug APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Upload APK to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: Code-Crow-Corp/Mage-Android
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk
          notifyTesters: true
          debug: false
